domain:
  dx: 100
  shape: 80
initial_conditions:
  center:
  - 40
  - 40
  - 40
  deformation_strength: 0.3
  nutrient:
    concentration: 1.0
    concentration_max: 1.0
    concentration_min: 0.0
    type: natural
  radius: 5
  seeding_densities:
    Necrotic Cells: 0.0
    Stem Cells: 0.2
    Tumour Cells: 0.8
  type: gaussian_random_blob
integrator:
  min_sub_grid_size: 10
  padding: 10
  threshold: 1e-6
  type: adaptive_grid
nutrient:
  color: Orange
  dynamics:
    boundary_value: 1.0
    diffusion: 700
    k: 0.05
  label: General nutrient
  name: General
physics:
  adhesion_energy:
    m: 0
populations:
  Necrotic:
    color: Black
    dynamics:
      beta_N: 1.0e-05
      lambda: 0.0
      mobility: 0.0
      mu: 5
      nutrient_consumption: 0.0
      nutrient_production: 0.0
      nutrient_threshold: 0.0
    label: Necrotic Cells
  Stem:
    color: Green
    dynamics:
      lambda: 70
      mobility: 1
      mu: 10
      nutrient_consumption: 0.1
      nutrient_production: 0.05
      nutrient_threshold: 0.5
    label: Stem Cells
    transfer:
      rate: 0.05
      to: Tumour
  Tumour:
    color: Green
    dynamics:
      lambda: 50
      mobility: 1
      mu: 10
      nutrient_consumption: 0.1
      nutrient_production: 0.05
      nutrient_threshold: 0.5
    label: Tumour Cells
simulation:
  name: CSC-T-N Model
  seed: 1209
time:
  dt: 0.05
  steps: 10
